---
global:
  timeout: 3
  storage:
    module: DBM_File
    file: /tmp/moxy.ndbm
    dbm_class: NDBM_File

plugins:
  - module: Filter::ControlPanel
  - module: Filter::XMLisHTML
  - module: Filter::UserAgentSwitcher
  - module: Filter::Pictogram
  - module: Filter::DisplayWidth
  - module: Filter::QRCode
  - module: Filter::RefererCutter
  - module: Filter::ShowHTTPHeaders
  - module: Filter::CookieCutter
  - module: Filter::HTTPHeader
  - module: Filter::FlashUseImgTag
  - module: Filter::DisableTableTag
  - module: Filter::GPS
# - module: Filter::QRCode::Imager
  - module: Filter::UserID
  - module: Filter::LocationBar

